"use client";

import { useEffect, useState } from "react";
import {
  Card,
  CardContent,
  Box,
  Typography,
  Stack,
  Avatar,
  Chip,
  Skeleton,
} from "@mui/material";
import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";
import WarningAmberRoundedIcon from "@mui/icons-material/WarningAmberRounded";
import TrendingUpRoundedIcon from "@mui/icons-material/TrendingUpRounded";
import PaidRoundedIcon from "@mui/icons-material/PaidRounded";
import Inventory2RoundedIcon from "@mui/icons-material/Inventory2Rounded";
import ScheduleRoundedIcon from "@mui/icons-material/ScheduleRounded";
import { gradients } from "@/lib/theme";

const ICONS = {
  reorder: <WarningAmberRoundedIcon />,
  trend: <TrendingUpRoundedIcon />,
  revenue: <PaidRoundedIcon />,
  deadstock: <Inventory2RoundedIcon />,
  timing: <ScheduleRoundedIcon />,
};
const SEV_COLOR = { high: "#F16A70", medium: "#F0C05A", low: "#8FE3B8" };

export default function InsightsCard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/insights")
      .then((r) => r.json())
      .then((res) => setData(res.data || null))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  return (
    <Card sx={{ height: "100%", position: "relative", overflow: "hidden", border: "none", color: "#fff", background: "#161B2B" }}>
      <Box sx={{ position: "absolute", inset: 0, background: gradients.mesh, opacity: 0.85 }} />
      <CardContent sx={{ position: "relative", p: 3 }}>
        <Stack direction="row" alignItems="center" spacing={1.25} sx={{ mb: 2 }}>
          <Avatar sx={{ width: 34, height: 34, background: gradients.brand, animation: "pulseGlow 3s ease-in-out infinite" }}>
            <AutoAwesomeRoundedIcon sx={{ fontSize: 18 }} />
          </Avatar>
          <Box sx={{ flex: 1 }}>
            <Typography variant="subtitle1" sx={{ color: "#fff", lineHeight: 1.1 }}>
              AI Smart Insights
            </Typography>
            <Typography variant="caption" sx={{ color: "rgba(255,255,255,0.6)" }}>
              {data?.generatedBy === "ai" ? "Generated by Claude" : "Updated just now"}
            </Typography>
          </Box>
        </Stack>

        {loading ? (
          <Stack spacing={1.5}>
            <Skeleton variant="rounded" height={44} sx={{ bgcolor: "rgba(255,255,255,0.08)" }} />
            <Skeleton variant="rounded" height={44} sx={{ bgcolor: "rgba(255,255,255,0.08)" }} />
            <Skeleton variant="rounded" height={44} sx={{ bgcolor: "rgba(255,255,255,0.08)" }} />
          </Stack>
        ) : !data || data.insights.length === 0 ? (
          <Typography variant="body2" sx={{ color: "rgba(255,255,255,0.8)", py: 2 }}>
            {data?.hasData
              ? "Everything looks healthy — no actions needed right now. 🎉"
              : "Add products and record a few sales to unlock insights."}
          </Typography>
        ) : (
          <>
            <Box
              sx={{
                p: 1.75,
                mb: 2,
                borderRadius: 3,
                background: "rgba(255,255,255,0.08)",
                border: "1px solid rgba(255,255,255,0.12)",
              }}
            >
              <Typography variant="body2" sx={{ color: "#fff", fontWeight: 600 }}>
                {data.headline}
              </Typography>
            </Box>
            <Stack spacing={1.25}>
              {data.insights.slice(0, 5).map((ins, i) => (
                <Stack
                  key={i}
                  direction="row"
                  spacing={1.25}
                  alignItems="flex-start"
                  sx={{
                    p: 1.5,
                    borderRadius: 2.5,
                    background: "rgba(255,255,255,0.05)",
                    border: "1px solid rgba(255,255,255,0.07)",
                    animation: "fadeUp .5s ease both",
                    animationDelay: `${i * 0.06}s`,
                  }}
                >
                  <Avatar sx={{ width: 30, height: 30, bgcolor: "rgba(255,255,255,0.1)", color: SEV_COLOR[ins.severity] }}>
                    {ICONS[ins.type] || <AutoAwesomeRoundedIcon fontSize="small" />}
                  </Avatar>
                  <Box sx={{ flex: 1, minWidth: 0 }}>
                    <Typography variant="caption" sx={{ color: "rgba(255,255,255,0.55)", display: "block" }}>
                      {ins.title}
                    </Typography>
                    <Typography variant="body2" sx={{ color: "rgba(255,255,255,0.92)" }}>
                      {ins.text}
                    </Typography>
                  </Box>
                </Stack>
              ))}
            </Stack>
          </>
        )}
      </CardContent>
    </Card>
  );
}
